--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:55:01 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(NULL, 'chandramohite@gmail.com', 1, 1);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(NULL, 'chandramohite@gmail.com', 2, 1);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'ss dsd dff weed ew', 3, 0);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'vds sdvasfd sdffad dsasfsda asdfs', 4, 0);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'vds sdvasfd sdffad dsasfsda asdfs', 5, 0);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'vds sdvasfd sdffad dsasfsda asdfs', 6, 0);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'aad dfvsd dfgbdfgb dfg', 7, 0);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'Tindlu Kodige halli Main Road, Near Ganesh Medicalk Store', 8, 1);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'Near Delivery Adress', 9, 1);
INSERT INTO myorganicstore.t_adress(userId, adress, adressId, Active) VALUES
(14, 'Near Raghavendr Math Doddabommasandra', 10, 1);