--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:55:01 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(1, 'Grocery/Grains and Lintels', 1);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(2, 'Sweeteners ', 1);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(3, 'Milk Products', 1);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(4, 'Vegetables', 1);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(5, 'other1', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(6, 'other2', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(7, 'other3', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(8, 'Other', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(9, 'Other', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(10, 'Others', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(11, 'Others1', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(12, 'Other', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(13, 'Others', 0);
INSERT INTO myorganicstore.t_category(categoryId, categoryName, Active) VALUES
(14, 'Other', 1);