--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:55:01 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(1, '8J5GQphs', 14, '2015-11-06 17:13:46', 'chandramohite@gmail.com', '82f2cc35074b1279906554d1c6ac029b', 10, 101.00, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(2, '7rZUYRYJ', 14, '2015-11-06 17:16:25', 'chandramohite@gmail.com', '82f2cc35074b1279906554d1c6ac029b', 10, 0.00, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(3, '53vKn2wS', 14, '2015-11-06 17:27:09', 'chandramohite@gmail.com', '82f2cc35074b1279906554d1c6ac029b', 9, 391.20, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(4, '4CWnIS62', 14, '2015-11-06 17:31:59', 'chandramohite@gmail.com', '82f2cc35074b1279906554d1c6ac029b', 9, 0.00, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(5, 'dCB9kYCD', 14, '2015-11-06 17:34:31', 'chandramohite@gmail.com', 'd931370e57443c32b8260f565eac3bb1', 10, 121.20, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(6, '6PTSEPza', 14, '2015-11-06 18:35:03', 'chandramohite@gmail.com', '28f69df645a2bb65fce86b5d2e689478', 9, 262.60, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(7, 'Kj4XzhAr', 14, '2015-11-06 20:20:43', 'chandramohite@gmail.com', '8da732331bf6a66b930a75ebd5459f6e', 8, 672.20, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(8, 'NbCZ5pRh', 14, '2015-11-06 21:57:50', 'chandramohite@gmail.com', '8da732331bf6a66b930a75ebd5459f6e', 8, 290.80, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(9, 'PkQC7Yzp', 14, '2015-11-06 22:09:46', 'chandramohite@gmail.com', '5d1e6fd27b88618fe2737be08ced4e32', 9, 702.20, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(10, 'gAW542ma', 14, '2015-11-06 22:11:39', 'chandramohite@gmail.com', '5d1e6fd27b88618fe2737be08ced4e32', 10, 70.40, 1);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(11, 'Z24u86a3', 14, '2015-11-06 23:35:14', 'chandramohite@gmail.com', '1c71dd718e759dff2141b60b429f4218', 8, 183.00, 0);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(12, '6haKP5T9', 14, '2015-11-06 23:35:24', 'chandramohite@gmail.com', '1c71dd718e759dff2141b60b429f4218', 8, 101.00, 0);
INSERT INTO myorganicstore.t_orderindex(orderId, orderCode, userId, orderDate, email, sid, addressId, orderCost, Active) VALUES
(13, 'k4V4zZPj', 14, '2015-11-06 23:35:44', 'chandramohite@gmail.com', '1c71dd718e759dff2141b60b429f4218', 10, 242.40, 0);