--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:59:19 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(1, 'PLACED', '2015-11-06 17:13:46');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(1, 'PLACED', '2015-11-06 17:16:25');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(1, 'PLACED', '2015-11-06 17:27:09');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(1, 'PLACED', '2015-11-06 17:31:59');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(5, 'PLACED', '2015-11-06 17:34:31');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(6, 'PLACED', '2015-11-06 18:35:03');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(7, 'PLACED', '2015-11-06 20:20:43');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(7, 'PLACED', '2015-11-06 21:57:50');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(9, 'PLACED', '2015-11-06 22:09:46');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(9, 'PLACED', '2015-11-06 22:11:39');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(11, 'PLACED', '2015-11-06 22:18:44');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(12, 'PLACED', '2015-11-06 22:19:40');
INSERT INTO myorganicstore.t_orderstate(orderId, orderStatus, changeDate) VALUES
(13, 'PLACED', '2015-11-06 23:07:44');