--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:55:01 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 11, 'Carrot', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 2, 'Wheat', 20.20, 'kg', 20.20, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 14, 'Tomato', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 11, 'Carrot', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 7, 'Methi', 20.20, 'gm', 20.20, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 19, 'Butter', 150.00, 'kg', 150.00, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 5, 'Toor Dal', 20.20, 'kg', 20.20, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 20, 'Paneer', 120.00, 'kg', 120.00, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(1, 14, 'Tomato', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(5, 13, 'Ladies Fingre', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(5, 10, 'raddish', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(5, 14, 'Tomato', 40.40, 'kg', 40.40, 0);
INSERT INTO myorganicstore.t_orderregistry(orderId, productId, productName, productUnitPrice, productUnit, productPrice, productQty) VALUES
(6, 1, 'Rice', 82.00, 'kg', 82.00, 0);