--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:59:35 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('02b8f98ebb3686f30f39872cd6b4ab82', '2', '3', '2015-10-21 17:18:43', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('02b8f98ebb3686f30f39872cd6b4ab82', '2', '3', '2015-10-21 17:19:45', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('02b8f98ebb3686f30f39872cd6b4ab82', '2', '3', '2015-10-21 17:21:16', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('02b8f98ebb3686f30f39872cd6b4ab82', '2', '3', '2015-10-21 17:23:08', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('02b8f98ebb3686f30f39872cd6b4ab82', '2', '3', '2015-10-21 17:29:37', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('e4d0e7527ceec119ae4e86d00d4174cd', '2', '3', '2015-10-21 18:45:23', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('2ca16a57ff0f23b762208b9fa086f088', '2', '3', '2015-10-21 18:52:18', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 18:57:49', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:00:41', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:02:25', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:04:47', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:04:58', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:09:50', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:11:26', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:11:52', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:12:59', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('3265cf3fa1350547940da3e9e592e092', '2', '3', '2015-10-21 19:13:09', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('193c795d31d9483490d4a8f53df94497', '2', '3', '2015-10-21 19:22:35', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('d56ce30be6f27b912239ffc61ab14a00', '2', '3', '2015-10-21 19:23:42', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('780703b0be6071df5b1dca5fc12dd4ff', '2', '3', '2015-10-21 19:24:05', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('e0988a5045bbf689a84bf0edf69829c6', '2', '3', '2015-10-21 19:24:56', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('ecd7888bfbc966c6997a26492a947040', '2', '3', '2015-10-21 19:27:05', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('977229386b6ba2e024e8f173a507b8ec', '2', '3', '2015-10-21 19:28:24', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('ed6325e0aaa475dc92e88d6b65dcc3e6', '2', '3', '2015-10-21 19:31:27', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('b60c43990081c6ce6165dc44054c7d68', '2', '3', '2015-10-21 19:32:06', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('e586b3cd4186895b840ae3f0ce5b17da', '2', '3', '2015-10-21 19:32:18', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('e825b0ecf9f7a2e9c05fdfa5f203c9ea', '2', '3', '2015-10-21 19:33:07', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('0d37e445e21ba4801d5decef2a5c1a3c', '2', '3', '2015-10-21 22:13:55', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('644b71d0edd7a031c9c265514713d72b', '2', '3', '2015-10-22 10:15:49', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('5b87cbcd13a100666c04a4dc6f08eeb6', '2', '3', '2015-10-22 10:19:05', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('df37f0343094e4421e58a40bb1d79b6c', '2', '3', '2015-10-22 10:19:37', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('c79fd5fa013f95058fa17b2ca0ab74ca', '2', '3', '2015-10-22 10:20:28', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('14eb24dd209b752d2740ff9b80d41c84', '2', '3', '2015-10-22 10:20:54', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('5fa4fb86e3db8ea18ad18fdc10dbdffc', '2', '3', '2015-10-22 10:21:46', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('d11c913b4291a50f4646b00de1f98225', '2', '3', '2015-10-22 10:23:27', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('df02c877d35bfb6f3cfc1c129334f5e3', '2', '3', '2015-10-22 10:24:04', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('f7a10a08c613cb7b26504ad82f3363a3', '2', '3', '2015-10-22 12:20:51', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('9b167ba57c29769a2ce928c84b3dee29', '2', '3', '2015-10-22 12:52:09', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('8104e18098c293f36b06d4134eb4bf5d', '12', '1', '2015-10-22 14:32:53', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('048227dafcfc3b3b284360f26d31dd27', '13', '1', '2015-10-22 15:56:38', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('c9ccade7923cda6ce6546ca1a922f942', '2', '3', '2015-10-22 16:18:54', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('6f6dbbf9c4f8af504526b5d739d8fb32', '13', '1', '2015-10-22 18:48:07', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('657d2228a61b960d39ae97b05abfa66a', '13', '1', '2015-10-22 20:48:21', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('c533f4c286744abb31a9a838553714e1', '12', '1', '2015-10-22 23:55:24', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('73d7b9a4c84aa5ca28b0e069fd98bbeb', '13', '1', '2015-10-23 09:59:11', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('c61218390735c9ffec9f9e1e2fe23c01', '13', '1', '2015-10-23 11:36:34', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('e0608e1f635c347761991a168bebabd7', '13', '1', '2015-10-23 11:46:48', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('06209f3614352d4affaffdbc26f15f38', '13', '1', '2015-10-23 13:10:50', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('82b0c0b4dfe2c74c7dd05e9d5a6a2d0c', '13', '1', '2015-10-23 13:21:58', True, False, '0000-00-00 00:00:00', NULL);
INSERT INTO myorganicstore.t_persession(sid, uid, role, logged_time, is_logged_in, is_logged_out, logged_out, orders) VALUES
('82b0c0b4dfe2c74c7dd05e9d5a6a2d0c', '14', '1', '2015-10-23 13:22:33', True, False, '0000-00-00 00:00:00', NULL);