--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/6/2015 11:59:48 PM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(1, 'Rice', 1, '1.jpg', 82.00, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(2, 'Wheat', 1, 'wheat.jpg', 20.20, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(3, 'Raagi', 1, 'raagi.jpg', 20.20, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(4, 'Urad Dal', 2, 'urad_dhal.jpg', 20.20, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(5, 'Toor Dal', 2, 'toor_dhal.jpg', 20.20, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(6, 'Green Gram', 2, 'green_gram.jpg', 20.20, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(7, 'Methi', 10, 'methi.jpg', 20.20, 'gm', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(8, 'Spinich', 10, 'spinich.jpg', 40.40, 'gm', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(9, 'Palakh', 10, 'palak.jpg', 40.40, 'gm', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(10, 'raddish', 11, 'raddish.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(11, 'Carrot', 11, 'carrot.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(12, 'Brinjal', 11, 'brinjal.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(13, 'Ladies Fingre', 11, 'lady_finger.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(14, 'Tomato', 11, 'tomato.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(15, 'potato', 11, 'potato.jpg', 40.40, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(16, 'Oats', 1, '16.jpg', 110.00, 'kg', 0);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(17, 'Juwar', 1, '17.jpg', 30.00, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(18, 'Ghee', 19, '18.jpg', 120.00, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(19, 'Butter', 19, '19.jpg', 150.00, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(20, 'Paneer', 19, '20.jpg', 120.00, 'kg', 1);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(21, 'Soya Beans', 1, '21.jpg', 70.00, 'kg', 0);
INSERT INTO myorganicstore.t_product(productId, productName, subCategoryId, productImage, productPrice, productUnit, Active) VALUES
(22, 'pumpkin', 11, '22.jpg', 30.00, 'kg', 1);