--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/7/2015 12:00:19 AM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';
