--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/7/2015 12:00:03 AM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(1, 'Grains', 1, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(2, 'pulses', 1, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(3, 'Millets', 1, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(4, 'Jaggery', 2, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(5, 'Honey', 2, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(6, 'Sugar', 2, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(7, 'Ghee', 3, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(8, 'Paneer', 3, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(9, 'Butter', 3, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(10, 'Leafy Veggies', 4, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(11, 'Non-Leafy Veggies', 4, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(12, 'others', 1, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(13, 'others', 4, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(14, 'other_Sub1', 13, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(15, 'other_Sub2', 13, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(16, 'other_sub11', 14, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(17, 'other_sub21', 14, 0);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(18, 'Glucose Syrup', 2, 1);
INSERT INTO myorganicstore.t_subcategory(subCategoryId, subCategoryName, CategoryId, Active) VALUES
(19, 'Cow Milk Based', 3, 1);