--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/7/2015 12:00:31 AM
-- Server version: 5.6.21-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Shivaprasad', 'Nanjundachari', 'nnsprasad@gmail.com', '202cb962ac59075b964b07152d234b70', '#28,11th cross, SirMV layout,Thindlu, VIdyaranyapura post Bangalore', '9900104439', '3', 2, 1, NULL);
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Shivaprasad', 'Nanjundachari', 'nnsprasad1@gmail.com', 'OTšÕZ‹W)·åwï ?', '74 4th Block Doddabommasandra', ' 919900104439', '1', 9, 1, '560096');
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Shivaprasad', 'Nanjundachari', 'nnsprassad@gmail.com', 'md5(myorganicstore)', '74 4th Block Doddabommasandra', ' 919900104439', '1', 10, 1, '560096');
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Shivaprasad', 'Nanjundachari', 'nsnsprasad@gmail.com', 'OTšÕZ‹W)·åwï ?', '74 4th Block Doddabommasandra', ' 919900104439', '1', 11, 1, '560096');
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Shivaprasad', 'Nanjundachari', 'nnccsprasad@gmail.com', '164f549ad55a8b572904b7e577ef203f', '74 4th Block Doddabommasandra', ' 919900104439', '1', 12, 1, '560096');
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('Srividya', 'Ananthachar', 'srividya2281@gmail.com', '164f549ad55a8b572904b7e577ef203f', '74 4th Block Doddabommasandra', ' 919900104439', '1', 13, 1, '560096');
INSERT INTO myorganicstore.t_user(firstname, lastname, email, usr_key, adress, phone, role, usr_id, Active, Zip) VALUES
('chandra', 'Rao', 'chandramohite@gmail.com', '202cb962ac59075b964b07152d234b70', 'Tindlu', '919743023111', '1', 14, 1, '560096');